name: Build
'on':
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: e658769f-d5fe-406f-9db5-8034fd75114a
          SONAR_TOKEN: 811c9a490983734401ba4e491eaefc8bfa7281de
          args: >-
            -Dsonar.projectKey=iamneo-production_e658769f-d5fe-406f-9db5-8034fd75114a
            -Dsonar.organization=iamneo-production -Dsonar.sources=
            -Dsonar.verbose=true
